engines:
  duplication:
    minTokenMatch: 70
    skipLexicalErrors: false
    ignoreLiterals: false
    ignoreIdentifiers: false
    ignoreAnnotations: false
    ignoreUsings: false
exclude_paths:
  - ".appveyor/**"
  - ".coverity/**"
  - ".github/**"
  - "Doxygen/**"
  - "examples/**"
  - "info/**"
  - "**/*.md"
  - "*.md"
  - "test/**"
  - "test/**"
  - "src/levenshtein/**"
  - "src/stx/**"
  - "src/nanoSVG/**"
 
