exclude_paths:
  - ".appveyor/**"
  - ".coverity/**"
  - ".github/**"
  - "Doxygen/**"
  - "examples/**"
  - "info/**"
  - "**/*.md"
  - "*.md"
  - "test/**"
  - "test/**"
  - "src/levenshtein/**"
  - "src/stx/**"
  - "src/nanoSVG/**"
 
