env:
  global:
    secure: iqwJ3Ilyyf7hVw3c/B0XXXvvesvDmZfOth5APO8sqGNsu8AMApoPjwngUyoMsNizmPa81sLinfQpF7htMKJx2jtSRt/W9nIk95RoDA9zy3DuX+IGVLcvai4y5E9EVUBfe+9vNP+ONXw1aFCJie4Q2GLd31WvmaSamLxvzgUe0/HPq4ERiUNw637wEQuRHNxKjj8Q9kcwiYm0Dxl+ioiBreUcXIhmdCrHgXZWu45/le+FS2erBllwsYbcDd/aXPh3DI5ZKooRxb4UERMbhSzP40gzwS6N5n8UXrzoLJlhwsE7EDQ9jp3fJwluhYqE2xeALXmZr1DjRpU3E5PqXy0Ya0LUnCs88wgU/0yewgpYdBTDRTDB60r2UQPKXcs+ePvOwrvlIlnEUi9UJiIcpl3PSUotdfVmFF7X0+OOpozCLoFyFPxeWqql97YsXKkn42bXMU+NBIdem+LTGplVscIqGZIuCMLvbx6YS8JM0++vgSneSeaGdDSnfYxKNfWNT2CIkeAkZfdo+bIzzLeZbleNH3EkJKNbuIyTl8TTpa7EBswc4KLTLFR42DibEcYhp+7mbtnLhsGpz8Th9cYajw6AFD6E3hSFgpP834Va0Kxty7fNesyEZCLvOtIcVq/6S5Az2ZmBgkzxLlrmk5Xf/2qd1R0239zUSeOEMl8y+Gl9bTI=
addons:
  apt_packages:
    - appstream-util
    - cmake
    - desktop-file-utils
    - doxygen
    - gettext
    - gnuplot
    - gnuplot-x11
    - graphviz
    - libwxgtk3.0-gtk3-dev
    - libwxgtk-webview3.0-gtk3-dev
    - maxima
    - maxima-share
    - maxima-doc
    - netcat-openbsd
    - ninja-build
    - build-essential
    - pandoc
    - xvfb
    - at-spi2-core
  coverity_scan:
    project:
      name: wxMaxima-developers/wxmaxima
      version: 1.0
      description: wxMaxima
    notification_email: scan_notifications@peterpall.dexx
    build_command_prepend: mkdir build&&cd build && cmake ..&&cd ..
    build_command: cd build&&make -j 4&&cd ..
    branch_pattern: main
