# Set up Cygwin. Source: https://github.com/egor-tensin/setup-cygwin
name: compile_cygwin

on: [push]

permissions:
  contents: read


jobs:
  setup_cygwin:
    runs-on: windows-latest
    steps:
      - run: |
             git config --global core.autocrlf input
             git config --global --add safe.directory /cygdrive/d/a/wxmaxima/wxmaxima
      - name: setup_cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: git cmake libwx_baseu3.1-devel libwx_gtk3u3.1-devel gcc-core gcc-g++ make gettext-devel
      - name: Checkout_git
        uses: actions/checkout@v4
      - name: configure
        run: |
             mkdir build
             cd build
             cmake ../wxmaxima
             cd ..
      - name: compile
        run: |
             cd build
             make VERBOSE=1 -j 4
             cd ..
